//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.DataLine9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Characteristic_type.
    /// </summary>
    //  *** Start programmer edit section *** (characteristic_type CustomAttributes)

    //  *** End programmer edit section *** (characteristic_type CustomAttributes)
    [PublishName("DataLine.ProtoOne.CharacteristicType")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("characteristic_typeE", new string[] {
            "regex as \'Regex\'",
            "description as \'Description\'"})]
    [View("characteristic_typeL", new string[] {
            "regex as \'Regex\'",
            "description as \'Description\'"})]
    public class characteristic_type : ICSSoft.STORMNET.DataObject
    {
        
        private string fregex;
        
        private string fdescription;
        
        //  *** Start programmer edit section *** (characteristic_type CustomMembers)

        //  *** End programmer edit section *** (characteristic_type CustomMembers)

        
        /// <summary>
        /// regex.
        /// </summary>
        //  *** Start programmer edit section *** (characteristic_type.regex CustomAttributes)

        //  *** End programmer edit section *** (characteristic_type.regex CustomAttributes)
        [StrLen(255)]
        [PublishName("Regex")]
        public virtual string regex
        {
            get
            {
                //  *** Start programmer edit section *** (characteristic_type.regex Get start)

                //  *** End programmer edit section *** (characteristic_type.regex Get start)
                string result = this.fregex;
                //  *** Start programmer edit section *** (characteristic_type.regex Get end)

                //  *** End programmer edit section *** (characteristic_type.regex Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (characteristic_type.regex Set start)

                //  *** End programmer edit section *** (characteristic_type.regex Set start)
                this.fregex = value;
                //  *** Start programmer edit section *** (characteristic_type.regex Set end)

                //  *** End programmer edit section *** (characteristic_type.regex Set end)
            }
        }
        
        /// <summary>
        /// description.
        /// </summary>
        //  *** Start programmer edit section *** (characteristic_type.description CustomAttributes)

        //  *** End programmer edit section *** (characteristic_type.description CustomAttributes)
        [StrLen(255)]
        [PublishName("Description")]
        public virtual string description
        {
            get
            {
                //  *** Start programmer edit section *** (characteristic_type.description Get start)

                //  *** End programmer edit section *** (characteristic_type.description Get start)
                string result = this.fdescription;
                //  *** Start programmer edit section *** (characteristic_type.description Get end)

                //  *** End programmer edit section *** (characteristic_type.description Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (characteristic_type.description Set start)

                //  *** End programmer edit section *** (characteristic_type.description Set start)
                this.fdescription = value;
                //  *** Start programmer edit section *** (characteristic_type.description Set end)

                //  *** End programmer edit section *** (characteristic_type.description Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "characteristic_typeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View characteristic_typeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("characteristic_typeE", typeof(DataLine.DataLine9.characteristic_type));
                }
            }
            
            /// <summary>
            /// "characteristic_typeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View characteristic_typeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("characteristic_typeL", typeof(DataLine.DataLine9.characteristic_type));
                }
            }
        }
    }
}
