//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.DataLine9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Contragent.
    /// </summary>
    //  *** Start programmer edit section *** (contragent CustomAttributes)

    //  *** End programmer edit section *** (contragent CustomAttributes)
    [PublishName("DataLine.ProtoOne.Contragent")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("contragentE", new string[] {
            "name",
            "descr as \'Descr\'",
            "official_name as \'Official_name\'",
            "creator_id as \'Creator_id\'",
            "modifier_id as \'Modifier_id\'",
            "dt_created as \'Dt_created\'",
            "dt_modified as \'Dt_modified\'",
            "INN as \'INN\'",
            "guid1c as \'Guid1c\'",
            "archive as \'Archive\'",
            "dt_archive as \'Dt_archive\'",
            "archiver_id as \'Archiver_id\'",
            "archive_reason_id as \'Archive_reason_id\'",
            "customer_id as \'Customer_id\'",
            "customer_id.name"})]
    [View("contragentL", new string[] {
            "name",
            "descr as \'Descr\'",
            "official_name as \'Official_name\'",
            "creator_id as \'Creator_id\'",
            "modifier_id as \'Modifier_id\'",
            "dt_created as \'Dt_created\'",
            "dt_modified as \'Dt_modified\'",
            "INN as \'INN\'",
            "guid1c as \'Guid1c\'",
            "archive as \'Archive\'",
            "dt_archive as \'Dt_archive\'",
            "archiver_id as \'Archiver_id\'",
            "archive_reason_id as \'Archive_reason_id\'",
            "customer_id.name"})]
    public class contragent : ICSSoft.STORMNET.DataObject
    {
        
        private string fname;
        
        private string fdescr;
        
        private string fofficial_name;
        
        private int fcreator_id;
        
        private int fmodifier_id;
        
        private System.DateTime fdt_created;
        
        private System.DateTime fdt_modified;
        
        private string fINN;
        
        private System.Guid fguid1c;
        
        private bool farchive;
        
        private System.DateTime fdt_archive;
        
        private int farchiver_id;
        
        private int farchive_reason_id;
        
        private DataLine.DataLine9.customer fcustomer_id;
        
        //  *** Start programmer edit section *** (contragent CustomMembers)

        //  *** End programmer edit section *** (contragent CustomMembers)

        
        /// <summary>
        /// name.
        /// </summary>
        //  *** Start programmer edit section *** (contragent.name CustomAttributes)

        //  *** End programmer edit section *** (contragent.name CustomAttributes)
        [StrLen(255)]
        public virtual string name
        {
            get
            {
                //  *** Start programmer edit section *** (contragent.name Get start)

                //  *** End programmer edit section *** (contragent.name Get start)
                string result = this.fname;
                //  *** Start programmer edit section *** (contragent.name Get end)

                //  *** End programmer edit section *** (contragent.name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (contragent.name Set start)

                //  *** End programmer edit section *** (contragent.name Set start)
                this.fname = value;
                //  *** Start programmer edit section *** (contragent.name Set end)

                //  *** End programmer edit section *** (contragent.name Set end)
            }
        }
        
        /// <summary>
        /// descr.
        /// </summary>
        //  *** Start programmer edit section *** (contragent.descr CustomAttributes)

        //  *** End programmer edit section *** (contragent.descr CustomAttributes)
        [PublishName("Descr")]
        public virtual string descr
        {
            get
            {
                //  *** Start programmer edit section *** (contragent.descr Get start)

                //  *** End programmer edit section *** (contragent.descr Get start)
                string result = this.fdescr;
                //  *** Start programmer edit section *** (contragent.descr Get end)

                //  *** End programmer edit section *** (contragent.descr Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (contragent.descr Set start)

                //  *** End programmer edit section *** (contragent.descr Set start)
                this.fdescr = value;
                //  *** Start programmer edit section *** (contragent.descr Set end)

                //  *** End programmer edit section *** (contragent.descr Set end)
            }
        }
        
        /// <summary>
        /// official_name.
        /// </summary>
        //  *** Start programmer edit section *** (contragent.official_name CustomAttributes)

        //  *** End programmer edit section *** (contragent.official_name CustomAttributes)
        [StrLen(255)]
        [PublishName("OfficialName")]
        public virtual string official_name
        {
            get
            {
                //  *** Start programmer edit section *** (contragent.official_name Get start)

                //  *** End programmer edit section *** (contragent.official_name Get start)
                string result = this.fofficial_name;
                //  *** Start programmer edit section *** (contragent.official_name Get end)

                //  *** End programmer edit section *** (contragent.official_name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (contragent.official_name Set start)

                //  *** End programmer edit section *** (contragent.official_name Set start)
                this.fofficial_name = value;
                //  *** Start programmer edit section *** (contragent.official_name Set end)

                //  *** End programmer edit section *** (contragent.official_name Set end)
            }
        }
        
        /// <summary>
        /// creator_id.
        /// </summary>
        //  *** Start programmer edit section *** (contragent.creator_id CustomAttributes)

        //  *** End programmer edit section *** (contragent.creator_id CustomAttributes)
        [PublishName("CreatorId")]
        public virtual int creator_id
        {
            get
            {
                //  *** Start programmer edit section *** (contragent.creator_id Get start)

                //  *** End programmer edit section *** (contragent.creator_id Get start)
                int result = this.fcreator_id;
                //  *** Start programmer edit section *** (contragent.creator_id Get end)

                //  *** End programmer edit section *** (contragent.creator_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (contragent.creator_id Set start)

                //  *** End programmer edit section *** (contragent.creator_id Set start)
                this.fcreator_id = value;
                //  *** Start programmer edit section *** (contragent.creator_id Set end)

                //  *** End programmer edit section *** (contragent.creator_id Set end)
            }
        }
        
        /// <summary>
        /// modifier_id.
        /// </summary>
        //  *** Start programmer edit section *** (contragent.modifier_id CustomAttributes)

        //  *** End programmer edit section *** (contragent.modifier_id CustomAttributes)
        [PublishName("ModifierId")]
        public virtual int modifier_id
        {
            get
            {
                //  *** Start programmer edit section *** (contragent.modifier_id Get start)

                //  *** End programmer edit section *** (contragent.modifier_id Get start)
                int result = this.fmodifier_id;
                //  *** Start programmer edit section *** (contragent.modifier_id Get end)

                //  *** End programmer edit section *** (contragent.modifier_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (contragent.modifier_id Set start)

                //  *** End programmer edit section *** (contragent.modifier_id Set start)
                this.fmodifier_id = value;
                //  *** Start programmer edit section *** (contragent.modifier_id Set end)

                //  *** End programmer edit section *** (contragent.modifier_id Set end)
            }
        }
        
        /// <summary>
        /// dt_created.
        /// </summary>
        //  *** Start programmer edit section *** (contragent.dt_created CustomAttributes)

        //  *** End programmer edit section *** (contragent.dt_created CustomAttributes)
        [PublishName("DtCreated")]
        public virtual System.DateTime dt_created
        {
            get
            {
                //  *** Start programmer edit section *** (contragent.dt_created Get start)

                //  *** End programmer edit section *** (contragent.dt_created Get start)
                System.DateTime result = this.fdt_created;
                //  *** Start programmer edit section *** (contragent.dt_created Get end)

                //  *** End programmer edit section *** (contragent.dt_created Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (contragent.dt_created Set start)

                //  *** End programmer edit section *** (contragent.dt_created Set start)
                this.fdt_created = value;
                //  *** Start programmer edit section *** (contragent.dt_created Set end)

                //  *** End programmer edit section *** (contragent.dt_created Set end)
            }
        }
        
        /// <summary>
        /// dt_modified.
        /// </summary>
        //  *** Start programmer edit section *** (contragent.dt_modified CustomAttributes)

        //  *** End programmer edit section *** (contragent.dt_modified CustomAttributes)
        [PublishName("DtModified")]
        public virtual System.DateTime dt_modified
        {
            get
            {
                //  *** Start programmer edit section *** (contragent.dt_modified Get start)

                //  *** End programmer edit section *** (contragent.dt_modified Get start)
                System.DateTime result = this.fdt_modified;
                //  *** Start programmer edit section *** (contragent.dt_modified Get end)

                //  *** End programmer edit section *** (contragent.dt_modified Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (contragent.dt_modified Set start)

                //  *** End programmer edit section *** (contragent.dt_modified Set start)
                this.fdt_modified = value;
                //  *** Start programmer edit section *** (contragent.dt_modified Set end)

                //  *** End programmer edit section *** (contragent.dt_modified Set end)
            }
        }
        
        /// <summary>
        /// INN.
        /// </summary>
        //  *** Start programmer edit section *** (contragent.INN CustomAttributes)

        //  *** End programmer edit section *** (contragent.INN CustomAttributes)
        [StrLen(32)]
        [PublishName("Inn")]
        public virtual string INN
        {
            get
            {
                //  *** Start programmer edit section *** (contragent.INN Get start)

                //  *** End programmer edit section *** (contragent.INN Get start)
                string result = this.fINN;
                //  *** Start programmer edit section *** (contragent.INN Get end)

                //  *** End programmer edit section *** (contragent.INN Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (contragent.INN Set start)

                //  *** End programmer edit section *** (contragent.INN Set start)
                this.fINN = value;
                //  *** Start programmer edit section *** (contragent.INN Set end)

                //  *** End programmer edit section *** (contragent.INN Set end)
            }
        }
        
        /// <summary>
        /// guid1c.
        /// </summary>
        //  *** Start programmer edit section *** (contragent.guid1c CustomAttributes)

        //  *** End programmer edit section *** (contragent.guid1c CustomAttributes)
        [PublishName("Guid1c")]
        public virtual System.Guid guid1c
        {
            get
            {
                //  *** Start programmer edit section *** (contragent.guid1c Get start)

                //  *** End programmer edit section *** (contragent.guid1c Get start)
                System.Guid result = this.fguid1c;
                //  *** Start programmer edit section *** (contragent.guid1c Get end)

                //  *** End programmer edit section *** (contragent.guid1c Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (contragent.guid1c Set start)

                //  *** End programmer edit section *** (contragent.guid1c Set start)
                this.fguid1c = value;
                //  *** Start programmer edit section *** (contragent.guid1c Set end)

                //  *** End programmer edit section *** (contragent.guid1c Set end)
            }
        }
        
        /// <summary>
        /// archive.
        /// </summary>
        //  *** Start programmer edit section *** (contragent.archive CustomAttributes)

        //  *** End programmer edit section *** (contragent.archive CustomAttributes)
        [PublishName("Archive")]
        public virtual bool archive
        {
            get
            {
                //  *** Start programmer edit section *** (contragent.archive Get start)

                //  *** End programmer edit section *** (contragent.archive Get start)
                bool result = this.farchive;
                //  *** Start programmer edit section *** (contragent.archive Get end)

                //  *** End programmer edit section *** (contragent.archive Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (contragent.archive Set start)

                //  *** End programmer edit section *** (contragent.archive Set start)
                this.farchive = value;
                //  *** Start programmer edit section *** (contragent.archive Set end)

                //  *** End programmer edit section *** (contragent.archive Set end)
            }
        }
        
        /// <summary>
        /// dt_archive.
        /// </summary>
        //  *** Start programmer edit section *** (contragent.dt_archive CustomAttributes)

        //  *** End programmer edit section *** (contragent.dt_archive CustomAttributes)
        [PublishName("Dt_archive")]
        public virtual System.DateTime dt_archive
        {
            get
            {
                //  *** Start programmer edit section *** (contragent.dt_archive Get start)

                //  *** End programmer edit section *** (contragent.dt_archive Get start)
                System.DateTime result = this.fdt_archive;
                //  *** Start programmer edit section *** (contragent.dt_archive Get end)

                //  *** End programmer edit section *** (contragent.dt_archive Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (contragent.dt_archive Set start)

                //  *** End programmer edit section *** (contragent.dt_archive Set start)
                this.fdt_archive = value;
                //  *** Start programmer edit section *** (contragent.dt_archive Set end)

                //  *** End programmer edit section *** (contragent.dt_archive Set end)
            }
        }
        
        /// <summary>
        /// archiver_id.
        /// </summary>
        //  *** Start programmer edit section *** (contragent.archiver_id CustomAttributes)

        //  *** End programmer edit section *** (contragent.archiver_id CustomAttributes)
        [PublishName("ArchiverId")]
        public virtual int archiver_id
        {
            get
            {
                //  *** Start programmer edit section *** (contragent.archiver_id Get start)

                //  *** End programmer edit section *** (contragent.archiver_id Get start)
                int result = this.farchiver_id;
                //  *** Start programmer edit section *** (contragent.archiver_id Get end)

                //  *** End programmer edit section *** (contragent.archiver_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (contragent.archiver_id Set start)

                //  *** End programmer edit section *** (contragent.archiver_id Set start)
                this.farchiver_id = value;
                //  *** Start programmer edit section *** (contragent.archiver_id Set end)

                //  *** End programmer edit section *** (contragent.archiver_id Set end)
            }
        }
        
        /// <summary>
        /// archive_reason_id.
        /// </summary>
        //  *** Start programmer edit section *** (contragent.archive_reason_id CustomAttributes)

        //  *** End programmer edit section *** (contragent.archive_reason_id CustomAttributes)
        [PublishName("ArchiveReasonId")]
        public virtual int archive_reason_id
        {
            get
            {
                //  *** Start programmer edit section *** (contragent.archive_reason_id Get start)

                //  *** End programmer edit section *** (contragent.archive_reason_id Get start)
                int result = this.farchive_reason_id;
                //  *** Start programmer edit section *** (contragent.archive_reason_id Get end)

                //  *** End programmer edit section *** (contragent.archive_reason_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (contragent.archive_reason_id Set start)

                //  *** End programmer edit section *** (contragent.archive_reason_id Set start)
                this.farchive_reason_id = value;
                //  *** Start programmer edit section *** (contragent.archive_reason_id Set end)

                //  *** End programmer edit section *** (contragent.archive_reason_id Set end)
            }
        }
        
        /// <summary>
        /// Contragent.
        /// </summary>
        //  *** Start programmer edit section *** (contragent.customer_id CustomAttributes)

        //  *** End programmer edit section *** (contragent.customer_id CustomAttributes)
        [PropertyStorage(new string[] {
                "customer_id"})]
        [PublishName("CustomerId")]
        public virtual DataLine.DataLine9.customer customer_id
        {
            get
            {
                //  *** Start programmer edit section *** (contragent.customer_id Get start)

                //  *** End programmer edit section *** (contragent.customer_id Get start)
                DataLine.DataLine9.customer result = this.fcustomer_id;
                //  *** Start programmer edit section *** (contragent.customer_id Get end)

                //  *** End programmer edit section *** (contragent.customer_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (contragent.customer_id Set start)

                //  *** End programmer edit section *** (contragent.customer_id Set start)
                this.fcustomer_id = value;
                //  *** Start programmer edit section *** (contragent.customer_id Set end)

                //  *** End programmer edit section *** (contragent.customer_id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "contragentE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View contragentE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("contragentE", typeof(DataLine.DataLine9.contragent));
                }
            }
            
            /// <summary>
            /// "contragentL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View contragentL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("contragentL", typeof(DataLine.DataLine9.contragent));
                }
            }
        }
    }
}
