//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.DataLine9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Customer_acl.
    /// </summary>
    //  *** Start programmer edit section *** (customer_acl CustomAttributes)

    //  *** End programmer edit section *** (customer_acl CustomAttributes)
    [PublishName("DataLine.ProtoOne.CustomerAcl")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("customer_aclE", new string[] {
            "a_create as \'A_create\'",
            "a_read as \'A_read\'",
            "a_update as \'A_update\'",
            "a_delete as \'A_delete\'",
            "group_id as \'Group_id\'",
            "group_id.name as \'Name\'",
            "customer_id as \'Customer_id\'",
            "customer_id.name"})]
    [View("customer_aclL", new string[] {
            "a_create as \'A_create\'",
            "a_read as \'A_read\'",
            "a_update as \'A_update\'",
            "a_delete as \'A_delete\'",
            "group_id.name as \'Name\'",
            "customer_id.name"})]
    public class customer_acl : ICSSoft.STORMNET.DataObject
    {
        
        private bool fa_create;
        
        private bool fa_read;
        
        private bool fa_update;
        
        private bool fa_delete;
        
        private DataLine.DataLine9.grp fgroup_id;
        
        private DataLine.DataLine9.customer fcustomer_id;
        
        //  *** Start programmer edit section *** (customer_acl CustomMembers)

        //  *** End programmer edit section *** (customer_acl CustomMembers)

        
        /// <summary>
        /// a_create.
        /// </summary>
        //  *** Start programmer edit section *** (customer_acl.a_create CustomAttributes)

        //  *** End programmer edit section *** (customer_acl.a_create CustomAttributes)
        [PublishName("ACreate")]
        [NotNull()]
        public virtual bool a_create
        {
            get
            {
                //  *** Start programmer edit section *** (customer_acl.a_create Get start)

                //  *** End programmer edit section *** (customer_acl.a_create Get start)
                bool result = this.fa_create;
                //  *** Start programmer edit section *** (customer_acl.a_create Get end)

                //  *** End programmer edit section *** (customer_acl.a_create Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer_acl.a_create Set start)

                //  *** End programmer edit section *** (customer_acl.a_create Set start)
                this.fa_create = value;
                //  *** Start programmer edit section *** (customer_acl.a_create Set end)

                //  *** End programmer edit section *** (customer_acl.a_create Set end)
            }
        }
        
        /// <summary>
        /// a_read.
        /// </summary>
        //  *** Start programmer edit section *** (customer_acl.a_read CustomAttributes)

        //  *** End programmer edit section *** (customer_acl.a_read CustomAttributes)
        [PublishName("ARead")]
        [NotNull()]
        public virtual bool a_read
        {
            get
            {
                //  *** Start programmer edit section *** (customer_acl.a_read Get start)

                //  *** End programmer edit section *** (customer_acl.a_read Get start)
                bool result = this.fa_read;
                //  *** Start programmer edit section *** (customer_acl.a_read Get end)

                //  *** End programmer edit section *** (customer_acl.a_read Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer_acl.a_read Set start)

                //  *** End programmer edit section *** (customer_acl.a_read Set start)
                this.fa_read = value;
                //  *** Start programmer edit section *** (customer_acl.a_read Set end)

                //  *** End programmer edit section *** (customer_acl.a_read Set end)
            }
        }
        
        /// <summary>
        /// a_update.
        /// </summary>
        //  *** Start programmer edit section *** (customer_acl.a_update CustomAttributes)

        //  *** End programmer edit section *** (customer_acl.a_update CustomAttributes)
        [PublishName("AUpdate")]
        [NotNull()]
        public virtual bool a_update
        {
            get
            {
                //  *** Start programmer edit section *** (customer_acl.a_update Get start)

                //  *** End programmer edit section *** (customer_acl.a_update Get start)
                bool result = this.fa_update;
                //  *** Start programmer edit section *** (customer_acl.a_update Get end)

                //  *** End programmer edit section *** (customer_acl.a_update Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer_acl.a_update Set start)

                //  *** End programmer edit section *** (customer_acl.a_update Set start)
                this.fa_update = value;
                //  *** Start programmer edit section *** (customer_acl.a_update Set end)

                //  *** End programmer edit section *** (customer_acl.a_update Set end)
            }
        }
        
        /// <summary>
        /// a_delete.
        /// </summary>
        //  *** Start programmer edit section *** (customer_acl.a_delete CustomAttributes)

        //  *** End programmer edit section *** (customer_acl.a_delete CustomAttributes)
        [PublishName("ADelete")]
        [NotNull()]
        public virtual bool a_delete
        {
            get
            {
                //  *** Start programmer edit section *** (customer_acl.a_delete Get start)

                //  *** End programmer edit section *** (customer_acl.a_delete Get start)
                bool result = this.fa_delete;
                //  *** Start programmer edit section *** (customer_acl.a_delete Get end)

                //  *** End programmer edit section *** (customer_acl.a_delete Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer_acl.a_delete Set start)

                //  *** End programmer edit section *** (customer_acl.a_delete Set start)
                this.fa_delete = value;
                //  *** Start programmer edit section *** (customer_acl.a_delete Set end)

                //  *** End programmer edit section *** (customer_acl.a_delete Set end)
            }
        }
        
        /// <summary>
        /// Customer_acl.
        /// </summary>
        //  *** Start programmer edit section *** (customer_acl.group_id CustomAttributes)

        //  *** End programmer edit section *** (customer_acl.group_id CustomAttributes)
        [NotNull()]
        public virtual DataLine.DataLine9.grp group_id
        {
            get
            {
                //  *** Start programmer edit section *** (customer_acl.group_id Get start)

                //  *** End programmer edit section *** (customer_acl.group_id Get start)
                DataLine.DataLine9.grp result = this.fgroup_id;
                //  *** Start programmer edit section *** (customer_acl.group_id Get end)

                //  *** End programmer edit section *** (customer_acl.group_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer_acl.group_id Set start)

                //  *** End programmer edit section *** (customer_acl.group_id Set start)
                this.fgroup_id = value;
                //  *** Start programmer edit section *** (customer_acl.group_id Set end)

                //  *** End programmer edit section *** (customer_acl.group_id Set end)
            }
        }
        
        /// <summary>
        /// Customer_acl.
        /// </summary>
        //  *** Start programmer edit section *** (customer_acl.customer_id CustomAttributes)

        //  *** End programmer edit section *** (customer_acl.customer_id CustomAttributes)
        [PropertyStorage(new string[] {
                "customer_id"})]
        [PublishName("CustomerId")]
        [NotNull()]
        public virtual DataLine.DataLine9.customer customer_id
        {
            get
            {
                //  *** Start programmer edit section *** (customer_acl.customer_id Get start)

                //  *** End programmer edit section *** (customer_acl.customer_id Get start)
                DataLine.DataLine9.customer result = this.fcustomer_id;
                //  *** Start programmer edit section *** (customer_acl.customer_id Get end)

                //  *** End programmer edit section *** (customer_acl.customer_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer_acl.customer_id Set start)

                //  *** End programmer edit section *** (customer_acl.customer_id Set start)
                this.fcustomer_id = value;
                //  *** Start programmer edit section *** (customer_acl.customer_id Set end)

                //  *** End programmer edit section *** (customer_acl.customer_id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "customer_aclE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View customer_aclE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("customer_aclE", typeof(DataLine.DataLine9.customer_acl));
                }
            }
            
            /// <summary>
            /// "customer_aclL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View customer_aclL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("customer_aclL", typeof(DataLine.DataLine9.customer_acl));
                }
            }
        }
    }
}
