//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.DataLine9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Customer.
    /// </summary>
    //  *** Start programmer edit section *** (customer CustomAttributes)

    //  *** End programmer edit section *** (customer CustomAttributes)
    [PublishName("DataLine.ProtoOne.Customer")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("customerE", new string[] {
            "name",
            "descr as \'Descr\'",
            "service_manager_id as \'Service_manager_id\'",
            "creator_id as \'Creator_id\'",
            "modifier_id as \'Modifier_id\'",
            "dt_created as \'Dt_created\'",
            "dt_modified as \'Dt_modified\'",
            "archive as \'Archive\'",
            "dt_archive as \'Dt_archive\'",
            "archiver_id as \'Archiver_id\'",
            "archive_reason_id as \'Archive_reason_id\'",
            "internal as \'Internal\'",
            "telco as \'Telco\'",
            "office as \'Office\'",
            "barrier as \'Barrier\'",
            "pci_dss as \'Pci_dss\'",
            "federal_low_152 as \'Federal_low_152\'",
            "account_manager_id as \'Account_manager_id\'"})]
    [View("customerL", new string[] {
            "name",
            "descr as \'Descr\'",
            "service_manager_id as \'Service_manager_id\'",
            "creator_id as \'Creator_id\'",
            "modifier_id as \'Modifier_id\'",
            "dt_created as \'Dt_created\'",
            "dt_modified as \'Dt_modified\'",
            "archive as \'Archive\'",
            "dt_archive as \'Dt_archive\'",
            "archiver_id as \'Archiver_id\'",
            "archive_reason_id as \'Archive_reason_id\'",
            "internal as \'Internal\'",
            "telco as \'Telco\'",
            "office as \'Office\'",
            "barrier as \'Barrier\'",
            "pci_dss as \'Pci_dss\'",
            "federal_low_152 as \'Federal_low_152\'",
            "account_manager_id as \'Account_manager_id\'"})]
    public class customer : ICSSoft.STORMNET.DataObject
    {
        
        private string fname;
        
        private string fdescr;
        
        private int fservice_manager_id;
        
        private int fcreator_id;
        
        private int fmodifier_id;
        
        private System.DateTime fdt_created;
        
        private System.DateTime fdt_modified;
        
        private bool farchive;
        
        private System.DateTime fdt_archive;
        
        private int farchiver_id;
        
        private int farchive_reason_id;
        
        private bool finternal;
        
        private bool ftelco;
        
        private bool foffice;
        
        private bool fbarrier;
        
        private bool fpci_dss;
        
        private bool ffederal_low_152;
        
        private int faccount_manager_id;
        
        //  *** Start programmer edit section *** (customer CustomMembers)

        //  *** End programmer edit section *** (customer CustomMembers)

        
        /// <summary>
        /// name.
        /// </summary>
        //  *** Start programmer edit section *** (customer.name CustomAttributes)

        //  *** End programmer edit section *** (customer.name CustomAttributes)
        [StrLen(128)]
        public virtual string name
        {
            get
            {
                //  *** Start programmer edit section *** (customer.name Get start)

                //  *** End programmer edit section *** (customer.name Get start)
                string result = this.fname;
                //  *** Start programmer edit section *** (customer.name Get end)

                //  *** End programmer edit section *** (customer.name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.name Set start)

                //  *** End programmer edit section *** (customer.name Set start)
                this.fname = value;
                //  *** Start programmer edit section *** (customer.name Set end)

                //  *** End programmer edit section *** (customer.name Set end)
            }
        }
        
        /// <summary>
        /// descr.
        /// </summary>
        //  *** Start programmer edit section *** (customer.descr CustomAttributes)

        //  *** End programmer edit section *** (customer.descr CustomAttributes)
        [PublishName("Descr")]
        public virtual string descr
        {
            get
            {
                //  *** Start programmer edit section *** (customer.descr Get start)

                //  *** End programmer edit section *** (customer.descr Get start)
                string result = this.fdescr;
                //  *** Start programmer edit section *** (customer.descr Get end)

                //  *** End programmer edit section *** (customer.descr Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.descr Set start)

                //  *** End programmer edit section *** (customer.descr Set start)
                this.fdescr = value;
                //  *** Start programmer edit section *** (customer.descr Set end)

                //  *** End programmer edit section *** (customer.descr Set end)
            }
        }
        
        /// <summary>
        /// service_manager_id.
        /// </summary>
        //  *** Start programmer edit section *** (customer.service_manager_id CustomAttributes)

        //  *** End programmer edit section *** (customer.service_manager_id CustomAttributes)
        [PublishName("ServiceManagerId")]
        public virtual int service_manager_id
        {
            get
            {
                //  *** Start programmer edit section *** (customer.service_manager_id Get start)

                //  *** End programmer edit section *** (customer.service_manager_id Get start)
                int result = this.fservice_manager_id;
                //  *** Start programmer edit section *** (customer.service_manager_id Get end)

                //  *** End programmer edit section *** (customer.service_manager_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.service_manager_id Set start)

                //  *** End programmer edit section *** (customer.service_manager_id Set start)
                this.fservice_manager_id = value;
                //  *** Start programmer edit section *** (customer.service_manager_id Set end)

                //  *** End programmer edit section *** (customer.service_manager_id Set end)
            }
        }
        
        /// <summary>
        /// creator_id.
        /// </summary>
        //  *** Start programmer edit section *** (customer.creator_id CustomAttributes)

        //  *** End programmer edit section *** (customer.creator_id CustomAttributes)
        [PublishName("CreatorId")]
        public virtual int creator_id
        {
            get
            {
                //  *** Start programmer edit section *** (customer.creator_id Get start)

                //  *** End programmer edit section *** (customer.creator_id Get start)
                int result = this.fcreator_id;
                //  *** Start programmer edit section *** (customer.creator_id Get end)

                //  *** End programmer edit section *** (customer.creator_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.creator_id Set start)

                //  *** End programmer edit section *** (customer.creator_id Set start)
                this.fcreator_id = value;
                //  *** Start programmer edit section *** (customer.creator_id Set end)

                //  *** End programmer edit section *** (customer.creator_id Set end)
            }
        }
        
        /// <summary>
        /// modifier_id.
        /// </summary>
        //  *** Start programmer edit section *** (customer.modifier_id CustomAttributes)

        //  *** End programmer edit section *** (customer.modifier_id CustomAttributes)
        [PublishName("ModifierId")]
        public virtual int modifier_id
        {
            get
            {
                //  *** Start programmer edit section *** (customer.modifier_id Get start)

                //  *** End programmer edit section *** (customer.modifier_id Get start)
                int result = this.fmodifier_id;
                //  *** Start programmer edit section *** (customer.modifier_id Get end)

                //  *** End programmer edit section *** (customer.modifier_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.modifier_id Set start)

                //  *** End programmer edit section *** (customer.modifier_id Set start)
                this.fmodifier_id = value;
                //  *** Start programmer edit section *** (customer.modifier_id Set end)

                //  *** End programmer edit section *** (customer.modifier_id Set end)
            }
        }
        
        /// <summary>
        /// dt_created.
        /// </summary>
        //  *** Start programmer edit section *** (customer.dt_created CustomAttributes)

        //  *** End programmer edit section *** (customer.dt_created CustomAttributes)
        [PublishName("DtCreated")]
        [NotNull()]
        public virtual System.DateTime dt_created
        {
            get
            {
                //  *** Start programmer edit section *** (customer.dt_created Get start)

                //  *** End programmer edit section *** (customer.dt_created Get start)
                System.DateTime result = this.fdt_created;
                //  *** Start programmer edit section *** (customer.dt_created Get end)

                //  *** End programmer edit section *** (customer.dt_created Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.dt_created Set start)

                //  *** End programmer edit section *** (customer.dt_created Set start)
                this.fdt_created = value;
                //  *** Start programmer edit section *** (customer.dt_created Set end)

                //  *** End programmer edit section *** (customer.dt_created Set end)
            }
        }
        
        /// <summary>
        /// dt_modified.
        /// </summary>
        //  *** Start programmer edit section *** (customer.dt_modified CustomAttributes)

        //  *** End programmer edit section *** (customer.dt_modified CustomAttributes)
        [PublishName("DtModified")]
        [NotNull()]
        public virtual System.DateTime dt_modified
        {
            get
            {
                //  *** Start programmer edit section *** (customer.dt_modified Get start)

                //  *** End programmer edit section *** (customer.dt_modified Get start)
                System.DateTime result = this.fdt_modified;
                //  *** Start programmer edit section *** (customer.dt_modified Get end)

                //  *** End programmer edit section *** (customer.dt_modified Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.dt_modified Set start)

                //  *** End programmer edit section *** (customer.dt_modified Set start)
                this.fdt_modified = value;
                //  *** Start programmer edit section *** (customer.dt_modified Set end)

                //  *** End programmer edit section *** (customer.dt_modified Set end)
            }
        }
        
        /// <summary>
        /// archive.
        /// </summary>
        //  *** Start programmer edit section *** (customer.archive CustomAttributes)

        //  *** End programmer edit section *** (customer.archive CustomAttributes)
        [PublishName("Archive")]
        [NotNull()]
        public virtual bool archive
        {
            get
            {
                //  *** Start programmer edit section *** (customer.archive Get start)

                //  *** End programmer edit section *** (customer.archive Get start)
                bool result = this.farchive;
                //  *** Start programmer edit section *** (customer.archive Get end)

                //  *** End programmer edit section *** (customer.archive Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.archive Set start)

                //  *** End programmer edit section *** (customer.archive Set start)
                this.farchive = value;
                //  *** Start programmer edit section *** (customer.archive Set end)

                //  *** End programmer edit section *** (customer.archive Set end)
            }
        }
        
        /// <summary>
        /// dt_archive.
        /// </summary>
        //  *** Start programmer edit section *** (customer.dt_archive CustomAttributes)

        //  *** End programmer edit section *** (customer.dt_archive CustomAttributes)
        [PublishName("DtArchive")]
        public virtual System.DateTime dt_archive
        {
            get
            {
                //  *** Start programmer edit section *** (customer.dt_archive Get start)

                //  *** End programmer edit section *** (customer.dt_archive Get start)
                System.DateTime result = this.fdt_archive;
                //  *** Start programmer edit section *** (customer.dt_archive Get end)

                //  *** End programmer edit section *** (customer.dt_archive Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.dt_archive Set start)

                //  *** End programmer edit section *** (customer.dt_archive Set start)
                this.fdt_archive = value;
                //  *** Start programmer edit section *** (customer.dt_archive Set end)

                //  *** End programmer edit section *** (customer.dt_archive Set end)
            }
        }
        
        /// <summary>
        /// archiver_id.
        /// </summary>
        //  *** Start programmer edit section *** (customer.archiver_id CustomAttributes)

        //  *** End programmer edit section *** (customer.archiver_id CustomAttributes)
        [PublishName("ArchiverId")]
        public virtual int archiver_id
        {
            get
            {
                //  *** Start programmer edit section *** (customer.archiver_id Get start)

                //  *** End programmer edit section *** (customer.archiver_id Get start)
                int result = this.farchiver_id;
                //  *** Start programmer edit section *** (customer.archiver_id Get end)

                //  *** End programmer edit section *** (customer.archiver_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.archiver_id Set start)

                //  *** End programmer edit section *** (customer.archiver_id Set start)
                this.farchiver_id = value;
                //  *** Start programmer edit section *** (customer.archiver_id Set end)

                //  *** End programmer edit section *** (customer.archiver_id Set end)
            }
        }
        
        /// <summary>
        /// archive_reason_id.
        /// </summary>
        //  *** Start programmer edit section *** (customer.archive_reason_id CustomAttributes)

        //  *** End programmer edit section *** (customer.archive_reason_id CustomAttributes)
        [PublishName("ArchiveReasonId")]
        public virtual int archive_reason_id
        {
            get
            {
                //  *** Start programmer edit section *** (customer.archive_reason_id Get start)

                //  *** End programmer edit section *** (customer.archive_reason_id Get start)
                int result = this.farchive_reason_id;
                //  *** Start programmer edit section *** (customer.archive_reason_id Get end)

                //  *** End programmer edit section *** (customer.archive_reason_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.archive_reason_id Set start)

                //  *** End programmer edit section *** (customer.archive_reason_id Set start)
                this.farchive_reason_id = value;
                //  *** Start programmer edit section *** (customer.archive_reason_id Set end)

                //  *** End programmer edit section *** (customer.archive_reason_id Set end)
            }
        }
        
        /// <summary>
        /// internal.
        /// </summary>
        //  *** Start programmer edit section *** (customer.internal CustomAttributes)

        //  *** End programmer edit section *** (customer.internal CustomAttributes)
        [PublishName("Internal")]
        [NotNull()]
        public virtual bool @internal
        {
            get
            {
                //  *** Start programmer edit section *** (customer.internal Get start)

                //  *** End programmer edit section *** (customer.internal Get start)
                bool result = this.finternal;
                //  *** Start programmer edit section *** (customer.internal Get end)

                //  *** End programmer edit section *** (customer.internal Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.internal Set start)

                //  *** End programmer edit section *** (customer.internal Set start)
                this.finternal = value;
                //  *** Start programmer edit section *** (customer.internal Set end)

                //  *** End programmer edit section *** (customer.internal Set end)
            }
        }
        
        /// <summary>
        /// telco.
        /// </summary>
        //  *** Start programmer edit section *** (customer.telco CustomAttributes)

        //  *** End programmer edit section *** (customer.telco CustomAttributes)
        [PublishName("Telco")]
        [NotNull()]
        public virtual bool telco
        {
            get
            {
                //  *** Start programmer edit section *** (customer.telco Get start)

                //  *** End programmer edit section *** (customer.telco Get start)
                bool result = this.ftelco;
                //  *** Start programmer edit section *** (customer.telco Get end)

                //  *** End programmer edit section *** (customer.telco Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.telco Set start)

                //  *** End programmer edit section *** (customer.telco Set start)
                this.ftelco = value;
                //  *** Start programmer edit section *** (customer.telco Set end)

                //  *** End programmer edit section *** (customer.telco Set end)
            }
        }
        
        /// <summary>
        /// office.
        /// </summary>
        //  *** Start programmer edit section *** (customer.office CustomAttributes)

        //  *** End programmer edit section *** (customer.office CustomAttributes)
        [PublishName("Office")]
        [NotNull()]
        public virtual bool office
        {
            get
            {
                //  *** Start programmer edit section *** (customer.office Get start)

                //  *** End programmer edit section *** (customer.office Get start)
                bool result = this.foffice;
                //  *** Start programmer edit section *** (customer.office Get end)

                //  *** End programmer edit section *** (customer.office Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.office Set start)

                //  *** End programmer edit section *** (customer.office Set start)
                this.foffice = value;
                //  *** Start programmer edit section *** (customer.office Set end)

                //  *** End programmer edit section *** (customer.office Set end)
            }
        }
        
        /// <summary>
        /// barrier.
        /// </summary>
        //  *** Start programmer edit section *** (customer.barrier CustomAttributes)

        //  *** End programmer edit section *** (customer.barrier CustomAttributes)
        [PublishName("Barrier")]
        [NotNull()]
        public virtual bool barrier
        {
            get
            {
                //  *** Start programmer edit section *** (customer.barrier Get start)

                //  *** End programmer edit section *** (customer.barrier Get start)
                bool result = this.fbarrier;
                //  *** Start programmer edit section *** (customer.barrier Get end)

                //  *** End programmer edit section *** (customer.barrier Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.barrier Set start)

                //  *** End programmer edit section *** (customer.barrier Set start)
                this.fbarrier = value;
                //  *** Start programmer edit section *** (customer.barrier Set end)

                //  *** End programmer edit section *** (customer.barrier Set end)
            }
        }
        
        /// <summary>
        /// pci_dss.
        /// </summary>
        //  *** Start programmer edit section *** (customer.pci_dss CustomAttributes)

        //  *** End programmer edit section *** (customer.pci_dss CustomAttributes)
        [PublishName("PciCss")]
        public virtual bool pci_dss
        {
            get
            {
                //  *** Start programmer edit section *** (customer.pci_dss Get start)

                //  *** End programmer edit section *** (customer.pci_dss Get start)
                bool result = this.fpci_dss;
                //  *** Start programmer edit section *** (customer.pci_dss Get end)

                //  *** End programmer edit section *** (customer.pci_dss Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.pci_dss Set start)

                //  *** End programmer edit section *** (customer.pci_dss Set start)
                this.fpci_dss = value;
                //  *** Start programmer edit section *** (customer.pci_dss Set end)

                //  *** End programmer edit section *** (customer.pci_dss Set end)
            }
        }
        
        /// <summary>
        /// federal_low_152.
        /// </summary>
        //  *** Start programmer edit section *** (customer.federal_low_152 CustomAttributes)

        //  *** End programmer edit section *** (customer.federal_low_152 CustomAttributes)
        [PublishName("FederalLow152")]
        public virtual bool federal_low_152
        {
            get
            {
                //  *** Start programmer edit section *** (customer.federal_low_152 Get start)

                //  *** End programmer edit section *** (customer.federal_low_152 Get start)
                bool result = this.ffederal_low_152;
                //  *** Start programmer edit section *** (customer.federal_low_152 Get end)

                //  *** End programmer edit section *** (customer.federal_low_152 Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.federal_low_152 Set start)

                //  *** End programmer edit section *** (customer.federal_low_152 Set start)
                this.ffederal_low_152 = value;
                //  *** Start programmer edit section *** (customer.federal_low_152 Set end)

                //  *** End programmer edit section *** (customer.federal_low_152 Set end)
            }
        }
        
        /// <summary>
        /// account_manager_id.
        /// </summary>
        //  *** Start programmer edit section *** (customer.account_manager_id CustomAttributes)

        //  *** End programmer edit section *** (customer.account_manager_id CustomAttributes)
        [PublishName("AccountManagerId")]
        public virtual int account_manager_id
        {
            get
            {
                //  *** Start programmer edit section *** (customer.account_manager_id Get start)

                //  *** End programmer edit section *** (customer.account_manager_id Get start)
                int result = this.faccount_manager_id;
                //  *** Start programmer edit section *** (customer.account_manager_id Get end)

                //  *** End programmer edit section *** (customer.account_manager_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (customer.account_manager_id Set start)

                //  *** End programmer edit section *** (customer.account_manager_id Set start)
                this.faccount_manager_id = value;
                //  *** Start programmer edit section *** (customer.account_manager_id Set end)

                //  *** End programmer edit section *** (customer.account_manager_id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "customerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View customerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("customerE", typeof(DataLine.DataLine9.customer));
                }
            }
            
            /// <summary>
            /// "customerL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View customerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("customerL", typeof(DataLine.DataLine9.customer));
                }
            }
        }
    }
}
