//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.DataLine9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Grp.
    /// </summary>
    //  *** Start programmer edit section *** (grp CustomAttributes)

    //  *** End programmer edit section *** (grp CustomAttributes)
    [PublishName("DataLine.ProtoOne.Grp")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("grpE", new string[] {
            "name as \'Name\'",
            "description as \'Description\'",
            "imported as \'Imported\'"})]
    [View("grpL", new string[] {
            "name as \'Name\'",
            "description as \'Description\'",
            "imported as \'Imported\'"})]
    public class grp : ICSSoft.STORMNET.DataObject
    {
        
        private string fname;
        
        private string fdescription;
        
        private bool fimported;
        
        //  *** Start programmer edit section *** (grp CustomMembers)

        //  *** End programmer edit section *** (grp CustomMembers)

        
        /// <summary>
        /// name.
        /// </summary>
        //  *** Start programmer edit section *** (grp.name CustomAttributes)

        //  *** End programmer edit section *** (grp.name CustomAttributes)
        [StrLen(255)]
        [PublishName("Name")]
        [NotNull()]
        public virtual string name
        {
            get
            {
                //  *** Start programmer edit section *** (grp.name Get start)

                //  *** End programmer edit section *** (grp.name Get start)
                string result = this.fname;
                //  *** Start programmer edit section *** (grp.name Get end)

                //  *** End programmer edit section *** (grp.name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (grp.name Set start)

                //  *** End programmer edit section *** (grp.name Set start)
                this.fname = value;
                //  *** Start programmer edit section *** (grp.name Set end)

                //  *** End programmer edit section *** (grp.name Set end)
            }
        }
        
        /// <summary>
        /// description.
        /// </summary>
        //  *** Start programmer edit section *** (grp.description CustomAttributes)

        //  *** End programmer edit section *** (grp.description CustomAttributes)
        [StrLen(255)]
        [PublishName("Description")]
        public virtual string description
        {
            get
            {
                //  *** Start programmer edit section *** (grp.description Get start)

                //  *** End programmer edit section *** (grp.description Get start)
                string result = this.fdescription;
                //  *** Start programmer edit section *** (grp.description Get end)

                //  *** End programmer edit section *** (grp.description Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (grp.description Set start)

                //  *** End programmer edit section *** (grp.description Set start)
                this.fdescription = value;
                //  *** Start programmer edit section *** (grp.description Set end)

                //  *** End programmer edit section *** (grp.description Set end)
            }
        }
        
        /// <summary>
        /// imported.
        /// </summary>
        //  *** Start programmer edit section *** (grp.imported CustomAttributes)

        //  *** End programmer edit section *** (grp.imported CustomAttributes)
        [PublishName("Imported")]
        [NotNull()]
        public virtual bool imported
        {
            get
            {
                //  *** Start programmer edit section *** (grp.imported Get start)

                //  *** End programmer edit section *** (grp.imported Get start)
                bool result = this.fimported;
                //  *** Start programmer edit section *** (grp.imported Get end)

                //  *** End programmer edit section *** (grp.imported Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (grp.imported Set start)

                //  *** End programmer edit section *** (grp.imported Set start)
                this.fimported = value;
                //  *** Start programmer edit section *** (grp.imported Set end)

                //  *** End programmer edit section *** (grp.imported Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "grpE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View grpE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("grpE", typeof(DataLine.DataLine9.grp));
                }
            }
            
            /// <summary>
            /// "grpL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View grpL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("grpL", typeof(DataLine.DataLine9.grp));
                }
            }
        }
    }
}
