//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.DataLine9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Order_item.
    /// </summary>
    //  *** Start programmer edit section *** (order_item CustomAttributes)

    //  *** End programmer edit section *** (order_item CustomAttributes)
    [PublishName("DataLine.ProtoOne.OrderItem")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("order_itemE", new string[] {
            "action as \'Action\'",
            "price as \'Price\'",
            "dt_created as \'Dt_created\'",
            "dt_modified as \'Dt_modified\'",
            "log as \'Log\'",
            "state as \'State\'",
            "state.description as \'Description\'",
            "creator_id as \'Creator_id\'",
            "creator_id.login as \'Login\'",
            "service_order_id as \'Service_order_id\'",
            "service_order_id.description as \'Description\'",
            "clone_service_id as \'Clone_service_id\'",
            "clone_service_id.name as \'Name\'",
            "parent_id as \'Parent_id\'",
            "parent_id.action as \'Action\'",
            "service_id as \'Service_id\'",
            "service_id.name as \'Name\'",
            "modifier_id as \'Modifier_id\'",
            "modifier_id.login as \'Login\'",
            "clone_service_id as \'Clone_service_id\'",
            "clone_service_id.name as \'Name\'",
            "creator_id as \'Creator_id\'",
            "creator_id.login as \'Login\'",
            "service_id as \'Service_id\'",
            "service_id.name as \'Name\'",
            "state as \'State\'",
            "state.description as \'Description\'"})]
    [View("order_itemL", new string[] {
            "action as \'Action\'",
            "price as \'Price\'",
            "dt_created as \'Dt_created\'",
            "dt_modified as \'Dt_modified\'",
            "log as \'Log\'",
            "state as \'Description\'",
            "creator_id as \'Login\'",
            "service_order_id as \'Description\'",
            "clone_service_id as \'Name\'",
            "parent_id as \'Action\'",
            "service_id as \'Name\'",
            "modifier_id as \'Login\'",
            "clone_service_id as \'Name\'",
            "creator_id as \'Login\'",
            "service_id as \'Name\'",
            "state as \'Description\'"}, Hidden=new string[] {
            "state",
            "creator_id",
            "service_order_id",
            "clone_service_id",
            "parent_id",
            "service_id",
            "modifier_id",
            "clone_service_id",
            "creator_id",
            "service_id",
            "state"})]
    public class order_item : ICSSoft.STORMNET.DataObject
    {
        
        private string faction;
        
        private double fprice;
        
        private System.DateTime fdt_created;
        
        private System.DateTime fdt_modified;
        
        private string flog;
        
        private DataLine.DataLine9.usr fmodifier_id;
        
        private DataLine.DataLine9.service_order fservice_order_id;
        
        private DataLine.DataLine9.order_state fstate;
        
        private DataLine.DataLine9.service fservice_id;
        
        private DataLine.DataLine9.usr fcreator_id;
        
        private DataLine.DataLine9.service fclone_service_id;
        
        private DataLine.DataLine9.order_item fparent_id;
        
        //  *** Start programmer edit section *** (order_item CustomMembers)

        //  *** End programmer edit section *** (order_item CustomMembers)

        
        /// <summary>
        /// action.
        /// </summary>
        //  *** Start programmer edit section *** (order_item.action CustomAttributes)

        //  *** End programmer edit section *** (order_item.action CustomAttributes)
        [StrLen(32)]
        [PublishName("Action")]
        [NotNull()]
        public virtual string action
        {
            get
            {
                //  *** Start programmer edit section *** (order_item.action Get start)

                //  *** End programmer edit section *** (order_item.action Get start)
                string result = this.faction;
                //  *** Start programmer edit section *** (order_item.action Get end)

                //  *** End programmer edit section *** (order_item.action Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (order_item.action Set start)

                //  *** End programmer edit section *** (order_item.action Set start)
                this.faction = value;
                //  *** Start programmer edit section *** (order_item.action Set end)

                //  *** End programmer edit section *** (order_item.action Set end)
            }
        }
        
        /// <summary>
        /// price.
        /// </summary>
        //  *** Start programmer edit section *** (order_item.price CustomAttributes)

        //  *** End programmer edit section *** (order_item.price CustomAttributes)
        [PublishName("Price")]
        [NotNull()]
        public virtual double price
        {
            get
            {
                //  *** Start programmer edit section *** (order_item.price Get start)

                //  *** End programmer edit section *** (order_item.price Get start)
                double result = this.fprice;
                //  *** Start programmer edit section *** (order_item.price Get end)

                //  *** End programmer edit section *** (order_item.price Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (order_item.price Set start)

                //  *** End programmer edit section *** (order_item.price Set start)
                this.fprice = value;
                //  *** Start programmer edit section *** (order_item.price Set end)

                //  *** End programmer edit section *** (order_item.price Set end)
            }
        }
        
        /// <summary>
        /// dt_created.
        /// </summary>
        //  *** Start programmer edit section *** (order_item.dt_created CustomAttributes)

        //  *** End programmer edit section *** (order_item.dt_created CustomAttributes)
        [PublishName("DtCreated")]
        [NotNull()]
        public virtual System.DateTime dt_created
        {
            get
            {
                //  *** Start programmer edit section *** (order_item.dt_created Get start)

                //  *** End programmer edit section *** (order_item.dt_created Get start)
                System.DateTime result = this.fdt_created;
                //  *** Start programmer edit section *** (order_item.dt_created Get end)

                //  *** End programmer edit section *** (order_item.dt_created Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (order_item.dt_created Set start)

                //  *** End programmer edit section *** (order_item.dt_created Set start)
                this.fdt_created = value;
                //  *** Start programmer edit section *** (order_item.dt_created Set end)

                //  *** End programmer edit section *** (order_item.dt_created Set end)
            }
        }
        
        /// <summary>
        /// dt_modified.
        /// </summary>
        //  *** Start programmer edit section *** (order_item.dt_modified CustomAttributes)

        //  *** End programmer edit section *** (order_item.dt_modified CustomAttributes)
        [PublishName("DtModified")]
        [NotNull()]
        public virtual System.DateTime dt_modified
        {
            get
            {
                //  *** Start programmer edit section *** (order_item.dt_modified Get start)

                //  *** End programmer edit section *** (order_item.dt_modified Get start)
                System.DateTime result = this.fdt_modified;
                //  *** Start programmer edit section *** (order_item.dt_modified Get end)

                //  *** End programmer edit section *** (order_item.dt_modified Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (order_item.dt_modified Set start)

                //  *** End programmer edit section *** (order_item.dt_modified Set start)
                this.fdt_modified = value;
                //  *** Start programmer edit section *** (order_item.dt_modified Set end)

                //  *** End programmer edit section *** (order_item.dt_modified Set end)
            }
        }
        
        /// <summary>
        /// log.
        /// </summary>
        //  *** Start programmer edit section *** (order_item.log CustomAttributes)

        //  *** End programmer edit section *** (order_item.log CustomAttributes)
        [StrLen(1024)]
        [PublishName("Log")]
        public virtual string log
        {
            get
            {
                //  *** Start programmer edit section *** (order_item.log Get start)

                //  *** End programmer edit section *** (order_item.log Get start)
                string result = this.flog;
                //  *** Start programmer edit section *** (order_item.log Get end)

                //  *** End programmer edit section *** (order_item.log Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (order_item.log Set start)

                //  *** End programmer edit section *** (order_item.log Set start)
                this.flog = value;
                //  *** Start programmer edit section *** (order_item.log Set end)

                //  *** End programmer edit section *** (order_item.log Set end)
            }
        }
        
        /// <summary>
        /// Order_item.
        /// </summary>
        //  *** Start programmer edit section *** (order_item.modifier_id CustomAttributes)

        //  *** End programmer edit section *** (order_item.modifier_id CustomAttributes)
        [PropertyStorage(new string[] {
                "modifier_id"})]
        public virtual DataLine.DataLine9.usr modifier_id
        {
            get
            {
                //  *** Start programmer edit section *** (order_item.modifier_id Get start)

                //  *** End programmer edit section *** (order_item.modifier_id Get start)
                DataLine.DataLine9.usr result = this.fmodifier_id;
                //  *** Start programmer edit section *** (order_item.modifier_id Get end)

                //  *** End programmer edit section *** (order_item.modifier_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (order_item.modifier_id Set start)

                //  *** End programmer edit section *** (order_item.modifier_id Set start)
                this.fmodifier_id = value;
                //  *** Start programmer edit section *** (order_item.modifier_id Set end)

                //  *** End programmer edit section *** (order_item.modifier_id Set end)
            }
        }
        
        /// <summary>
        /// Order_item.
        /// </summary>
        //  *** Start programmer edit section *** (order_item.service_order_id CustomAttributes)

        //  *** End programmer edit section *** (order_item.service_order_id CustomAttributes)
        [PropertyStorage(new string[] {
                "service_order_id"})]
        [NotNull()]
        public virtual DataLine.DataLine9.service_order service_order_id
        {
            get
            {
                //  *** Start programmer edit section *** (order_item.service_order_id Get start)

                //  *** End programmer edit section *** (order_item.service_order_id Get start)
                DataLine.DataLine9.service_order result = this.fservice_order_id;
                //  *** Start programmer edit section *** (order_item.service_order_id Get end)

                //  *** End programmer edit section *** (order_item.service_order_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (order_item.service_order_id Set start)

                //  *** End programmer edit section *** (order_item.service_order_id Set start)
                this.fservice_order_id = value;
                //  *** Start programmer edit section *** (order_item.service_order_id Set end)

                //  *** End programmer edit section *** (order_item.service_order_id Set end)
            }
        }
        
        /// <summary>
        /// Order_item.
        /// </summary>
        //  *** Start programmer edit section *** (order_item.state CustomAttributes)

        //  *** End programmer edit section *** (order_item.state CustomAttributes)
        [NotNull()]
        public virtual DataLine.DataLine9.order_state state
        {
            get
            {
                //  *** Start programmer edit section *** (order_item.state Get start)

                //  *** End programmer edit section *** (order_item.state Get start)
                DataLine.DataLine9.order_state result = this.fstate;
                //  *** Start programmer edit section *** (order_item.state Get end)

                //  *** End programmer edit section *** (order_item.state Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (order_item.state Set start)

                //  *** End programmer edit section *** (order_item.state Set start)
                this.fstate = value;
                //  *** Start programmer edit section *** (order_item.state Set end)

                //  *** End programmer edit section *** (order_item.state Set end)
            }
        }
        
        /// <summary>
        /// Order_item.
        /// </summary>
        //  *** Start programmer edit section *** (order_item.service_id CustomAttributes)

        //  *** End programmer edit section *** (order_item.service_id CustomAttributes)
        [NotNull()]
        public virtual DataLine.DataLine9.service service_id
        {
            get
            {
                //  *** Start programmer edit section *** (order_item.service_id Get start)

                //  *** End programmer edit section *** (order_item.service_id Get start)
                DataLine.DataLine9.service result = this.fservice_id;
                //  *** Start programmer edit section *** (order_item.service_id Get end)

                //  *** End programmer edit section *** (order_item.service_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (order_item.service_id Set start)

                //  *** End programmer edit section *** (order_item.service_id Set start)
                this.fservice_id = value;
                //  *** Start programmer edit section *** (order_item.service_id Set end)

                //  *** End programmer edit section *** (order_item.service_id Set end)
            }
        }
        
        /// <summary>
        /// Order_item.
        /// </summary>
        //  *** Start programmer edit section *** (order_item.creator_id CustomAttributes)

        //  *** End programmer edit section *** (order_item.creator_id CustomAttributes)
        [PropertyStorage(new string[] {
                "creator_id"})]
        public virtual DataLine.DataLine9.usr creator_id
        {
            get
            {
                //  *** Start programmer edit section *** (order_item.creator_id Get start)

                //  *** End programmer edit section *** (order_item.creator_id Get start)
                DataLine.DataLine9.usr result = this.fcreator_id;
                //  *** Start programmer edit section *** (order_item.creator_id Get end)

                //  *** End programmer edit section *** (order_item.creator_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (order_item.creator_id Set start)

                //  *** End programmer edit section *** (order_item.creator_id Set start)
                this.fcreator_id = value;
                //  *** Start programmer edit section *** (order_item.creator_id Set end)

                //  *** End programmer edit section *** (order_item.creator_id Set end)
            }
        }
        
        /// <summary>
        /// Order_item.
        /// </summary>
        //  *** Start programmer edit section *** (order_item.clone_service_id CustomAttributes)

        //  *** End programmer edit section *** (order_item.clone_service_id CustomAttributes)
        [NotNull()]
        public virtual DataLine.DataLine9.service clone_service_id
        {
            get
            {
                //  *** Start programmer edit section *** (order_item.clone_service_id Get start)

                //  *** End programmer edit section *** (order_item.clone_service_id Get start)
                DataLine.DataLine9.service result = this.fclone_service_id;
                //  *** Start programmer edit section *** (order_item.clone_service_id Get end)

                //  *** End programmer edit section *** (order_item.clone_service_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (order_item.clone_service_id Set start)

                //  *** End programmer edit section *** (order_item.clone_service_id Set start)
                this.fclone_service_id = value;
                //  *** Start programmer edit section *** (order_item.clone_service_id Set end)

                //  *** End programmer edit section *** (order_item.clone_service_id Set end)
            }
        }
        
        /// <summary>
        /// Order_item.
        /// </summary>
        //  *** Start programmer edit section *** (order_item.parent_id CustomAttributes)

        //  *** End programmer edit section *** (order_item.parent_id CustomAttributes)
        [PropertyStorage(new string[] {
                "parent_id"})]
        public virtual DataLine.DataLine9.order_item parent_id
        {
            get
            {
                //  *** Start programmer edit section *** (order_item.parent_id Get start)

                //  *** End programmer edit section *** (order_item.parent_id Get start)
                DataLine.DataLine9.order_item result = this.fparent_id;
                //  *** Start programmer edit section *** (order_item.parent_id Get end)

                //  *** End programmer edit section *** (order_item.parent_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (order_item.parent_id Set start)

                //  *** End programmer edit section *** (order_item.parent_id Set start)
                this.fparent_id = value;
                //  *** Start programmer edit section *** (order_item.parent_id Set end)

                //  *** End programmer edit section *** (order_item.parent_id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "order_itemE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View order_itemE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("order_itemE", typeof(DataLine.DataLine9.order_item));
                }
            }
            
            /// <summary>
            /// "order_itemL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View order_itemL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("order_itemL", typeof(DataLine.DataLine9.order_item));
                }
            }
        }
    }
}
