//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.DataLine9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Resource_shared.
    /// </summary>
    //  *** Start programmer edit section *** (resource_shared CustomAttributes)

    //  *** End programmer edit section *** (resource_shared CustomAttributes)
    [PublishName("DataLine.ProtoOne.ResourceShared")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("resource_sharedE", new string[] {
            "external_id as \'External_id\'",
            "existent as \'Existent\'",
            "name as \'Name\'",
            "description as \'Description\'",
            "category as \'Category\'",
            "type as \'Type\'",
            "dt_created as \'Dt_created\'",
            "dt_modified as \'Dt_modified\'",
            "customer_id as \'Customer_id\'",
            "customer_id.name"})]
    [View("resource_sharedL", new string[] {
            "external_id as \'External_id\'",
            "existent as \'Existent\'",
            "name as \'Name\'",
            "description as \'Description\'",
            "category as \'Category\'",
            "type as \'Type\'",
            "dt_created as \'Dt_created\'",
            "dt_modified as \'Dt_modified\'",
            "customer_id.name"})]
    public class resource_shared : ICSSoft.STORMNET.DataObject
    {
        
        private string fexternal_id;
        
        private bool fexistent;
        
        private string fname;
        
        private string fdescription;
        
        private string fcategory;
        
        private string ftype;
        
        private System.DateTime fdt_created;
        
        private System.DateTime fdt_modified;
        
        private DataLine.DataLine9.customer fcustomer_id;
        
        //  *** Start programmer edit section *** (resource_shared CustomMembers)

        //  *** End programmer edit section *** (resource_shared CustomMembers)

        
        /// <summary>
        /// external_id.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.external_id CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.external_id CustomAttributes)
        [StrLen(128)]
        [PublishName("ExternalId")]
        public virtual string external_id
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.external_id Get start)

                //  *** End programmer edit section *** (resource_shared.external_id Get start)
                string result = this.fexternal_id;
                //  *** Start programmer edit section *** (resource_shared.external_id Get end)

                //  *** End programmer edit section *** (resource_shared.external_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.external_id Set start)

                //  *** End programmer edit section *** (resource_shared.external_id Set start)
                this.fexternal_id = value;
                //  *** Start programmer edit section *** (resource_shared.external_id Set end)

                //  *** End programmer edit section *** (resource_shared.external_id Set end)
            }
        }
        
        /// <summary>
        /// existent.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.existent CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.existent CustomAttributes)
        [PublishName("Existent")]
        [NotNull()]
        public virtual bool existent
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.existent Get start)

                //  *** End programmer edit section *** (resource_shared.existent Get start)
                bool result = this.fexistent;
                //  *** Start programmer edit section *** (resource_shared.existent Get end)

                //  *** End programmer edit section *** (resource_shared.existent Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.existent Set start)

                //  *** End programmer edit section *** (resource_shared.existent Set start)
                this.fexistent = value;
                //  *** Start programmer edit section *** (resource_shared.existent Set end)

                //  *** End programmer edit section *** (resource_shared.existent Set end)
            }
        }
        
        /// <summary>
        /// name.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.name CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.name CustomAttributes)
        [StrLen(255)]
        [PublishName("Name")]
        [NotNull()]
        public virtual string name
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.name Get start)

                //  *** End programmer edit section *** (resource_shared.name Get start)
                string result = this.fname;
                //  *** Start programmer edit section *** (resource_shared.name Get end)

                //  *** End programmer edit section *** (resource_shared.name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.name Set start)

                //  *** End programmer edit section *** (resource_shared.name Set start)
                this.fname = value;
                //  *** Start programmer edit section *** (resource_shared.name Set end)

                //  *** End programmer edit section *** (resource_shared.name Set end)
            }
        }
        
        /// <summary>
        /// description.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.description CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.description CustomAttributes)
        [PublishName("Description")]
        public virtual string description
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.description Get start)

                //  *** End programmer edit section *** (resource_shared.description Get start)
                string result = this.fdescription;
                //  *** Start programmer edit section *** (resource_shared.description Get end)

                //  *** End programmer edit section *** (resource_shared.description Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.description Set start)

                //  *** End programmer edit section *** (resource_shared.description Set start)
                this.fdescription = value;
                //  *** Start programmer edit section *** (resource_shared.description Set end)

                //  *** End programmer edit section *** (resource_shared.description Set end)
            }
        }
        
        /// <summary>
        /// category.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.category CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.category CustomAttributes)
        [StrLen(32)]
        [PublishName("Category")]
        [NotNull()]
        public virtual string category
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.category Get start)

                //  *** End programmer edit section *** (resource_shared.category Get start)
                string result = this.fcategory;
                //  *** Start programmer edit section *** (resource_shared.category Get end)

                //  *** End programmer edit section *** (resource_shared.category Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.category Set start)

                //  *** End programmer edit section *** (resource_shared.category Set start)
                this.fcategory = value;
                //  *** Start programmer edit section *** (resource_shared.category Set end)

                //  *** End programmer edit section *** (resource_shared.category Set end)
            }
        }
        
        /// <summary>
        /// type.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.type CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.type CustomAttributes)
        [StrLen(32)]
        [PublishName("Type")]
        [NotNull()]
        public virtual string type
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.type Get start)

                //  *** End programmer edit section *** (resource_shared.type Get start)
                string result = this.ftype;
                //  *** Start programmer edit section *** (resource_shared.type Get end)

                //  *** End programmer edit section *** (resource_shared.type Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.type Set start)

                //  *** End programmer edit section *** (resource_shared.type Set start)
                this.ftype = value;
                //  *** Start programmer edit section *** (resource_shared.type Set end)

                //  *** End programmer edit section *** (resource_shared.type Set end)
            }
        }
        
        /// <summary>
        /// dt_created.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.dt_created CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.dt_created CustomAttributes)
        [PublishName("DtCreated")]
        [NotNull()]
        public virtual System.DateTime dt_created
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.dt_created Get start)

                //  *** End programmer edit section *** (resource_shared.dt_created Get start)
                System.DateTime result = this.fdt_created;
                //  *** Start programmer edit section *** (resource_shared.dt_created Get end)

                //  *** End programmer edit section *** (resource_shared.dt_created Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.dt_created Set start)

                //  *** End programmer edit section *** (resource_shared.dt_created Set start)
                this.fdt_created = value;
                //  *** Start programmer edit section *** (resource_shared.dt_created Set end)

                //  *** End programmer edit section *** (resource_shared.dt_created Set end)
            }
        }
        
        /// <summary>
        /// dt_modified.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.dt_modified CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.dt_modified CustomAttributes)
        [PublishName("DtModified")]
        [NotNull()]
        public virtual System.DateTime dt_modified
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.dt_modified Get start)

                //  *** End programmer edit section *** (resource_shared.dt_modified Get start)
                System.DateTime result = this.fdt_modified;
                //  *** Start programmer edit section *** (resource_shared.dt_modified Get end)

                //  *** End programmer edit section *** (resource_shared.dt_modified Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.dt_modified Set start)

                //  *** End programmer edit section *** (resource_shared.dt_modified Set start)
                this.fdt_modified = value;
                //  *** Start programmer edit section *** (resource_shared.dt_modified Set end)

                //  *** End programmer edit section *** (resource_shared.dt_modified Set end)
            }
        }
        
        /// <summary>
        /// Resource_shared.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.customer_id CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.customer_id CustomAttributes)
        [PropertyStorage(new string[] {
                "customer_id"})]
        [PublishName("CustomerId")]
        [NotNull()]
        public virtual DataLine.DataLine9.customer customer_id
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.customer_id Get start)

                //  *** End programmer edit section *** (resource_shared.customer_id Get start)
                DataLine.DataLine9.customer result = this.fcustomer_id;
                //  *** Start programmer edit section *** (resource_shared.customer_id Get end)

                //  *** End programmer edit section *** (resource_shared.customer_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.customer_id Set start)

                //  *** End programmer edit section *** (resource_shared.customer_id Set start)
                this.fcustomer_id = value;
                //  *** Start programmer edit section *** (resource_shared.customer_id Set end)

                //  *** End programmer edit section *** (resource_shared.customer_id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "resource_sharedE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View resource_sharedE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("resource_sharedE", typeof(DataLine.DataLine9.resource_shared));
                }
            }
            
            /// <summary>
            /// "resource_sharedL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View resource_sharedL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("resource_sharedL", typeof(DataLine.DataLine9.resource_shared));
                }
            }
        }
    }
}
