//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.DataLine9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Service_usage_spec.
    /// </summary>
    //  *** Start programmer edit section *** (service_usage_spec CustomAttributes)

    //  *** End programmer edit section *** (service_usage_spec CustomAttributes)
    [PublishName("DataLine.ProtoOne.ServiceUsageSpec")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("service_usage_specE", new string[] {
            "name as \'Name\'",
            "value as \'Value\'",
            "map as \'Map\'",
            "unit as \'Unit\'",
            "type as \'Type\'",
            "type.regex as \'Regex\'",
            "service_spec_id as \'Service_spec_id\'",
            "service_spec_id.enum as \'Enum\'",
            "type as \'Type\'",
            "type.regex as \'Regex\'"})]
    [View("service_usage_specL", new string[] {
            "name as \'Name\'",
            "value as \'Value\'",
            "map as \'Map\'",
            "unit as \'Unit\'",
            "type.regex as \'Regex\'",
            "service_spec_id.enum as \'Enum\'",
            "type.regex as \'Regex\'"})]
    public class service_usage_spec : ICSSoft.STORMNET.DataObject
    {
        
        private string fname;
        
        private string fvalue;
        
        private bool fmap;
        
        private string funit;
        
        private DataLine.DataLine9.characteristic_type ftype;
        
        private DataLine.DataLine9.service_spec fservice_spec_id;
        
        //  *** Start programmer edit section *** (service_usage_spec CustomMembers)

        //  *** End programmer edit section *** (service_usage_spec CustomMembers)

        
        /// <summary>
        /// name.
        /// </summary>
        //  *** Start programmer edit section *** (service_usage_spec.name CustomAttributes)

        //  *** End programmer edit section *** (service_usage_spec.name CustomAttributes)
        [StrLen(255)]
        [PublishName("Name")]
        [NotNull()]
        public virtual string name
        {
            get
            {
                //  *** Start programmer edit section *** (service_usage_spec.name Get start)

                //  *** End programmer edit section *** (service_usage_spec.name Get start)
                string result = this.fname;
                //  *** Start programmer edit section *** (service_usage_spec.name Get end)

                //  *** End programmer edit section *** (service_usage_spec.name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_usage_spec.name Set start)

                //  *** End programmer edit section *** (service_usage_spec.name Set start)
                this.fname = value;
                //  *** Start programmer edit section *** (service_usage_spec.name Set end)

                //  *** End programmer edit section *** (service_usage_spec.name Set end)
            }
        }
        
        /// <summary>
        /// value.
        /// </summary>
        //  *** Start programmer edit section *** (service_usage_spec.value CustomAttributes)

        //  *** End programmer edit section *** (service_usage_spec.value CustomAttributes)
        [StrLen(255)]
        [PublishName("Value")]
        public virtual string value
        {
            get
            {
                //  *** Start programmer edit section *** (service_usage_spec.value Get start)

                //  *** End programmer edit section *** (service_usage_spec.value Get start)
                string result = this.fvalue;
                //  *** Start programmer edit section *** (service_usage_spec.value Get end)

                //  *** End programmer edit section *** (service_usage_spec.value Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_usage_spec.value Set start)

                //  *** End programmer edit section *** (service_usage_spec.value Set start)
                this.fvalue = value;
                //  *** Start programmer edit section *** (service_usage_spec.value Set end)

                //  *** End programmer edit section *** (service_usage_spec.value Set end)
            }
        }
        
        /// <summary>
        /// map.
        /// </summary>
        //  *** Start programmer edit section *** (service_usage_spec.map CustomAttributes)

        //  *** End programmer edit section *** (service_usage_spec.map CustomAttributes)
        [PublishName("Map")]
        [NotNull()]
        public virtual bool map
        {
            get
            {
                //  *** Start programmer edit section *** (service_usage_spec.map Get start)

                //  *** End programmer edit section *** (service_usage_spec.map Get start)
                bool result = this.fmap;
                //  *** Start programmer edit section *** (service_usage_spec.map Get end)

                //  *** End programmer edit section *** (service_usage_spec.map Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_usage_spec.map Set start)

                //  *** End programmer edit section *** (service_usage_spec.map Set start)
                this.fmap = value;
                //  *** Start programmer edit section *** (service_usage_spec.map Set end)

                //  *** End programmer edit section *** (service_usage_spec.map Set end)
            }
        }
        
        /// <summary>
        /// unit.
        /// </summary>
        //  *** Start programmer edit section *** (service_usage_spec.unit CustomAttributes)

        //  *** End programmer edit section *** (service_usage_spec.unit CustomAttributes)
        [StrLen(32)]
        [PublishName("Unit")]
        public virtual string unit
        {
            get
            {
                //  *** Start programmer edit section *** (service_usage_spec.unit Get start)

                //  *** End programmer edit section *** (service_usage_spec.unit Get start)
                string result = this.funit;
                //  *** Start programmer edit section *** (service_usage_spec.unit Get end)

                //  *** End programmer edit section *** (service_usage_spec.unit Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_usage_spec.unit Set start)

                //  *** End programmer edit section *** (service_usage_spec.unit Set start)
                this.funit = value;
                //  *** Start programmer edit section *** (service_usage_spec.unit Set end)

                //  *** End programmer edit section *** (service_usage_spec.unit Set end)
            }
        }
        
        /// <summary>
        /// Service_usage_spec.
        /// </summary>
        //  *** Start programmer edit section *** (service_usage_spec.type CustomAttributes)

        //  *** End programmer edit section *** (service_usage_spec.type CustomAttributes)
        [PropertyStorage(new string[] {
                "type"})]
        [PublishName("Type")]
        [NotNull()]
        public virtual DataLine.DataLine9.characteristic_type type
        {
            get
            {
                //  *** Start programmer edit section *** (service_usage_spec.type Get start)

                //  *** End programmer edit section *** (service_usage_spec.type Get start)
                DataLine.DataLine9.characteristic_type result = this.ftype;
                //  *** Start programmer edit section *** (service_usage_spec.type Get end)

                //  *** End programmer edit section *** (service_usage_spec.type Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_usage_spec.type Set start)

                //  *** End programmer edit section *** (service_usage_spec.type Set start)
                this.ftype = value;
                //  *** Start programmer edit section *** (service_usage_spec.type Set end)

                //  *** End programmer edit section *** (service_usage_spec.type Set end)
            }
        }
        
        /// <summary>
        /// Service_usage_spec.
        /// </summary>
        //  *** Start programmer edit section *** (service_usage_spec.service_spec_id CustomAttributes)

        //  *** End programmer edit section *** (service_usage_spec.service_spec_id CustomAttributes)
        [PropertyStorage(new string[] {
                "service_spec_id"})]
        [NotNull()]
        public virtual DataLine.DataLine9.service_spec service_spec_id
        {
            get
            {
                //  *** Start programmer edit section *** (service_usage_spec.service_spec_id Get start)

                //  *** End programmer edit section *** (service_usage_spec.service_spec_id Get start)
                DataLine.DataLine9.service_spec result = this.fservice_spec_id;
                //  *** Start programmer edit section *** (service_usage_spec.service_spec_id Get end)

                //  *** End programmer edit section *** (service_usage_spec.service_spec_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_usage_spec.service_spec_id Set start)

                //  *** End programmer edit section *** (service_usage_spec.service_spec_id Set start)
                this.fservice_spec_id = value;
                //  *** Start programmer edit section *** (service_usage_spec.service_spec_id Set end)

                //  *** End programmer edit section *** (service_usage_spec.service_spec_id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "service_usage_specE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View service_usage_specE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("service_usage_specE", typeof(DataLine.DataLine9.service_usage_spec));
                }
            }
            
            /// <summary>
            /// "service_usage_specL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View service_usage_specL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("service_usage_specL", typeof(DataLine.DataLine9.service_usage_spec));
                }
            }
        }
    }
}
