//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.DataLine9
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// User_service_spec.
    /// </summary>
    //  *** Start programmer edit section *** (user_service_spec CustomAttributes)

    //  *** End programmer edit section *** (user_service_spec CustomAttributes)
    [PublishName("DataLine.ProtoOne.UserServiceSpec")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("user_service_specE", new string[] {
            "action as \'Action\'",
            "dt_action as \'Dt_action\'",
            "service_spec_id as \'Service_spec_id\'",
            "service_spec_id.enum as \'Enum\'",
            "user_id as \'User_id\'",
            "user_id.login as \'Login\'"})]
    [View("user_service_specL", new string[] {
            "action as \'Action\'",
            "dt_action as \'Dt_action\'",
            "service_spec_id.enum as \'Enum\'",
            "user_id.login as \'Login\'"})]
    public class user_service_spec : ICSSoft.STORMNET.DataObject
    {
        
        private string faction;
        
        private System.DateTime fdt_action;
        
        private DataLine.DataLine9.usr fuser_id;
        
        private DataLine.DataLine9.service_spec fservice_spec_id;
        
        //  *** Start programmer edit section *** (user_service_spec CustomMembers)

        //  *** End programmer edit section *** (user_service_spec CustomMembers)

        
        /// <summary>
        /// action.
        /// </summary>
        //  *** Start programmer edit section *** (user_service_spec.action CustomAttributes)

        //  *** End programmer edit section *** (user_service_spec.action CustomAttributes)
        [StrLen(32)]
        [PublishName("Action")]
        [NotNull()]
        public virtual string action
        {
            get
            {
                //  *** Start programmer edit section *** (user_service_spec.action Get start)

                //  *** End programmer edit section *** (user_service_spec.action Get start)
                string result = this.faction;
                //  *** Start programmer edit section *** (user_service_spec.action Get end)

                //  *** End programmer edit section *** (user_service_spec.action Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (user_service_spec.action Set start)

                //  *** End programmer edit section *** (user_service_spec.action Set start)
                this.faction = value;
                //  *** Start programmer edit section *** (user_service_spec.action Set end)

                //  *** End programmer edit section *** (user_service_spec.action Set end)
            }
        }
        
        /// <summary>
        /// dt_action.
        /// </summary>
        //  *** Start programmer edit section *** (user_service_spec.dt_action CustomAttributes)

        //  *** End programmer edit section *** (user_service_spec.dt_action CustomAttributes)
        [PublishName("DtAction")]
        [NotNull()]
        public virtual System.DateTime dt_action
        {
            get
            {
                //  *** Start programmer edit section *** (user_service_spec.dt_action Get start)

                //  *** End programmer edit section *** (user_service_spec.dt_action Get start)
                System.DateTime result = this.fdt_action;
                //  *** Start programmer edit section *** (user_service_spec.dt_action Get end)

                //  *** End programmer edit section *** (user_service_spec.dt_action Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (user_service_spec.dt_action Set start)

                //  *** End programmer edit section *** (user_service_spec.dt_action Set start)
                this.fdt_action = value;
                //  *** Start programmer edit section *** (user_service_spec.dt_action Set end)

                //  *** End programmer edit section *** (user_service_spec.dt_action Set end)
            }
        }
        
        /// <summary>
        /// User_service_spec.
        /// </summary>
        //  *** Start programmer edit section *** (user_service_spec.user_id CustomAttributes)

        //  *** End programmer edit section *** (user_service_spec.user_id CustomAttributes)
        [PropertyStorage(new string[] {
                "user_id"})]
        [NotNull()]
        public virtual DataLine.DataLine9.usr user_id
        {
            get
            {
                //  *** Start programmer edit section *** (user_service_spec.user_id Get start)

                //  *** End programmer edit section *** (user_service_spec.user_id Get start)
                DataLine.DataLine9.usr result = this.fuser_id;
                //  *** Start programmer edit section *** (user_service_spec.user_id Get end)

                //  *** End programmer edit section *** (user_service_spec.user_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (user_service_spec.user_id Set start)

                //  *** End programmer edit section *** (user_service_spec.user_id Set start)
                this.fuser_id = value;
                //  *** Start programmer edit section *** (user_service_spec.user_id Set end)

                //  *** End programmer edit section *** (user_service_spec.user_id Set end)
            }
        }
        
        /// <summary>
        /// User_service_spec.
        /// </summary>
        //  *** Start programmer edit section *** (user_service_spec.service_spec_id CustomAttributes)

        //  *** End programmer edit section *** (user_service_spec.service_spec_id CustomAttributes)
        [PropertyStorage(new string[] {
                "service_spec_id"})]
        [NotNull()]
        public virtual DataLine.DataLine9.service_spec service_spec_id
        {
            get
            {
                //  *** Start programmer edit section *** (user_service_spec.service_spec_id Get start)

                //  *** End programmer edit section *** (user_service_spec.service_spec_id Get start)
                DataLine.DataLine9.service_spec result = this.fservice_spec_id;
                //  *** Start programmer edit section *** (user_service_spec.service_spec_id Get end)

                //  *** End programmer edit section *** (user_service_spec.service_spec_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (user_service_spec.service_spec_id Set start)

                //  *** End programmer edit section *** (user_service_spec.service_spec_id Set start)
                this.fservice_spec_id = value;
                //  *** Start programmer edit section *** (user_service_spec.service_spec_id Set end)

                //  *** End programmer edit section *** (user_service_spec.service_spec_id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "user_service_specE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View user_service_specE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("user_service_specE", typeof(DataLine.DataLine9.user_service_spec));
                }
            }
            
            /// <summary>
            /// "user_service_specL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View user_service_specL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("user_service_specL", typeof(DataLine.DataLine9.user_service_spec));
                }
            }
        }
    }
}
